In [2]:
import numpy as np

In [3]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumOneNp.png" width="500">


In [4]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [8]:
# type of the array
type(a)

numpy.ndarray

In [9]:
# type of the values stored in numpy array
a.dtype

dtype('int64')

#Shape, ndim, Shape

In [11]:
a.size

5

In [12]:
a.ndim

1

In [16]:
b = np.array([[a]])
b.ndim

3

In [24]:
# 1-dimensional array
arr_1d = np.array([1, 2, 3])
print(f"Dimensions of arr_1d: {arr_1d.ndim}") # Output: 1

# 2-dimensional array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Dimensions of arr_2d: {arr_2d.ndim}") # Output: 2

# 3-dimensional array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"Dimensions of arr_3d: {arr_3d.ndim}") # Output: 3

Dimensions of arr_1d: 1
Dimensions of arr_2d: 2
Dimensions of arr_3d: 3


In [25]:
a.shape

(5,)

In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


#Array






[start:end:step]

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


#Numpy Statistical Functions

In [28]:
a.mean()

2.0

In [29]:
a.max()

4

In [30]:
a.min()

0

In [31]:
a.std()

1.4142135623730951

In [36]:
a

array([0, 1, 2, 3, 4])

In [35]:
b = np.array([2,2,2,2,2])
c = np.add(a,b)
c

array([2, 3, 4, 5, 6])

In [37]:
d = np.subtract(a,b)
d

array([-2, -1,  0,  1,  2])

In [38]:
e = a+10
e

array([10, 11, 12, 13, 14])

#.linspace

numpy.linspace(start, stop, num = int value)

start : start of interval range

stop : end of interval range

num : Number of samples to generate.

In [40]:
np.linspace(-2, 2, num=5)

array([-2., -1.,  0.,  1.,  2.])

In [46]:
y = np.linspace(0, 49, num=50)
y

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [47]:
z = np.linspace(1, 50, num=50)
z

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

#Note [[]] and []

- dataframe_name["column_name"] # Accesses single column
- dataframe_name[["column1", "column2"]] # Accesses multiple columns

- df.drop(["age", "salary"], axis=1, inplace=True) # Will drop columns
- df.drop(index=[5, 10], axis=0, inplace=True) # Will drop rows

- duplicate_rows = df[df.duplicated()]

- df["status"].replace("In Progress", "Active", inplace=True) #Replaces specific values in a column with new values.

- array_1d = np.array([1, 2, 3]) # 1D Array
- array_2d = np.array([[1, 2], [3, 4]]) # 2D Array

#2D Numpy

In [48]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFT.png" width="400">


In [51]:
A = np.array(a) # Convert list to Numpy Array, # Every element is the same type
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [52]:
A[1, 2]

23

In [53]:
A[1][2]

23

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFSF.png" width="400">


In [64]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

In [65]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])